<?php
/**
 * @file
 * Code for the Bibsdb Edit Events feature.
 */

include_once 'bibsdb_event.features.inc';

/**
 * Disable caching of Event-nodes, so that events with sales-periods
 * are made available for sale at the correct time.
 */
function bibsdb_event_init() {    
  // Get the current active node object if present.
	$node = menu_get_object();
	if (!empty($node) && !empty($node->type) && $node->type == 'ding_event') {
		drupal_page_is_cacheable(FALSE);
	}
}

/**
 * Implements hook_form_alter()
 * Count chars in lead. More than 255 chars will break Place2book integration
 */

function bibsdb_event_form_ding_event_node_form_alter(&$form, &$form_state, $form_id) {
  $form['#attached']['js'][] = drupal_get_path('module', 'bibsdb_event') . '/js/bibsdb_event.js';
}
